(define (problem example-auv)
  (:domain suave)

  (:objects 
    f_generate_search_path f_follow_pipeline f_maintain_motion fd_spiral_low fd_spiral_medium fd_spiral_high fd_all_thrusters fd_recover_thrusters fd_follow_pipeline  qa_search_efficiency_medium performance qa_water_visibility_high qa_water_visibility_low qa_water_visibility_medium c_thruster_4 qa_search_efficiency_high qa_motion_efficiency_degraded qa_inspect_efficiency_high qa_search_efficiency_low c_thruster_6 c_thruster_2 qa_motion_efficiency_normal obs_water_visibility c_thruster_3 c_thruster_5 c_thruster_1 safety energy battery_level - object 
    a_search_pipeline a_inspect_pipeline - action 
    pipeline - pipeline 
    bluerov - robot 
)

  (:init
    (fd_available fd_spiral_low)
    (fd_available fd_spiral_medium)
    (fd_available fd_spiral_high)
    (fd_available fd_all_thrusters)
    (fd_available fd_recover_thrusters)
    (fd_available fd_follow_pipeline)
    
    (a_search_pipeline_requires_f a_search_pipeline f_generate_search_path f_maintain_motion)
    (a_inspect_pipeline_requires_f a_inspect_pipeline f_follow_pipeline f_maintain_motion)
    
    (isQAtype qa_search_efficiency_medium performance)
    (isQAtype qa_water_visibility_high water_visibility)
    (isQAtype qa_water_visibility_low water_visibility)
    (hasQAestimation fd_spiral_medium qa_water_visibility_medium)
    (isQAtype qa_water_visibility_medium water_visibility)
    (requiredBy c_thruster_4 fd_all_thrusters)
    (solvesF fd_spiral_medium f_generate_search_path)
    (isQAtype qa_search_efficiency_high performance)
    (hasQAestimation fd_recover_thrusters qa_motion_efficiency_degraded)
    (hasQAestimation fd_follow_pipeline qa_inspect_efficiency_high)
    (isQAtype qa_motion_efficiency_degraded performance)
    (hasQAestimation fd_spiral_low qa_search_efficiency_low)
    (solvesF fd_recover_thrusters f_maintain_motion)
    (requiredBy c_thruster_6 fd_all_thrusters)
    (solvesF fd_spiral_high f_generate_search_path)
    (requiredBy c_thruster_2 fd_all_thrusters)
    (hasQAestimation fd_spiral_high qa_water_visibility_high)
    (isQAtype qa_motion_efficiency_normal performance)
    (solvesF fd_all_thrusters f_maintain_motion)
    (isQAtype obs_water_visibility water_visibility)
    (hasQAestimation fd_spiral_high qa_search_efficiency_high)
    (solvesF fd_spiral_low f_generate_search_path)
    (requiredBy c_thruster_3 fd_all_thrusters)
    (isQAtype qa_inspect_efficiency_high performance)
    (hasQAestimation fd_spiral_medium qa_search_efficiency_medium)
    (solvesF fd_follow_pipeline f_follow_pipeline)
    (hasQAestimation fd_all_thrusters qa_motion_efficiency_normal)
    (hasQAestimation fd_spiral_low qa_water_visibility_low)
    (requiredBy c_thruster_5 fd_all_thrusters)
    (isQAtype qa_search_efficiency_low performance)
    (requiredBy c_thruster_1 fd_all_thrusters)
    (Component c_thruster_3)
    (QualityAttributeType safety)
    (Function f_generate_search_path)
    (FunctionDesign fd_follow_pipeline)
    (QualityAttributeType energy)
    (QAvalue qa_search_efficiency_low)
    (Function f_maintain_motion)
    (FunctionDesign fd_all_thrusters)
    (QAvalue qa_water_visibility_medium)
    (Component c_thruster_5)
    (QualityAttributeType performance)
    (Component c_thruster_6)
    (QAvalue qa_motion_efficiency_normal)
    (FunctionDesign fd_spiral_high)
    (QAvalue obs_water_visibility)
    (QAvalue qa_water_visibility_low)
    (QAvalue qa_water_visibility_high)
    (QualityAttributeType battery_level)
    (Component c_thruster_1)
    (QAvalue qa_search_efficiency_high)
    (FunctionDesign fd_spiral_medium)
    (QAvalue qa_inspect_efficiency_high)
    (Component c_thruster_2)
    (QualityAttributeType water_visibility)
    (FunctionDesign fd_spiral_low)
    (QAvalue qa_search_efficiency_medium)
    (Component c_thruster_4)
    (FunctionDesign fd_recover_thrusters)
    (Function f_follow_pipeline)
    (QAvalue qa_motion_efficiency_degraded)
  )

  (:goal (and
    (robot_started bluerov)
    (pipeline_found pipeline)
    (pipeline_inspected pipeline)
  ))
)
