(define (problem example-auv)
  (:domain suave)

  (:objects 
    a_search_pipeline a_inspect_pipeline - action 
    pipeline - pipeline 
    bluerov - robot 
    fd_spiral_high qa_water_visibility_high fd_spiral_low qa_water_visibility_low fd_all_thrusters c_thruster_1 qa_search_efficiency_medium performance qa_search_efficiency_high c_thruster_6 qa_motion_efficiency_degraded f_generate_search_path qa_motion_efficiency_normal fd_recover_thrusters f_maintain_motion qa_water_visibility_medium qa_inspect_efficiency_high qa_search_efficiency_low obs_water_visibility fd_spiral_medium fd_follow_pipeline f_follow_pipeline c_thruster_4 c_thruster_3 c_thruster_2 c_thruster_5 safety battery_level energy - object 
)

  (:init
    (inferred-c_status c_thruster_4 false_string)
    
    (action_requires a_search_pipeline f_generate_search_path f_maintain_motion)
    (action_requires a_inspect_pipeline f_follow_pipeline f_maintain_motion)
    
    (hasQAestimation fd_spiral_high qa_water_visibility_high)
    (hasQAestimation fd_spiral_low qa_water_visibility_low)
    (requiresC fd_all_thrusters c_thruster_1)
    (isQAtype qa_search_efficiency_medium performance)
    (hasQAestimation fd_spiral_high qa_search_efficiency_high)
    (requiresC fd_all_thrusters c_thruster_6)
    (isQAtype qa_motion_efficiency_degraded performance)
    (isQAtype qa_search_efficiency_high performance)
    (solvesF fd_spiral_low f_generate_search_path)
    (hasQAestimation fd_all_thrusters qa_motion_efficiency_normal)
    (solvesF fd_recover_thrusters f_maintain_motion)
    (isQAtype qa_water_visibility_medium water_visibility)
    (isQAtype qa_inspect_efficiency_high performance)
    (isQAtype qa_motion_efficiency_normal performance)
    (isQAtype qa_search_efficiency_low performance)
    (solvesF fd_all_thrusters f_maintain_motion)
    (hasQAestimation fd_recover_thrusters qa_motion_efficiency_degraded)
    (isQAtype obs_water_visibility water_visibility)
    (hasQAestimation fd_spiral_medium qa_search_efficiency_medium)
    (solvesF fd_follow_pipeline f_follow_pipeline)
    (hasQAestimation fd_follow_pipeline qa_inspect_efficiency_high)
    (hasQAestimation fd_spiral_medium qa_water_visibility_medium)
    (requiresC fd_all_thrusters c_thruster_4)
    (isQAtype qa_water_visibility_high water_visibility)
    (requiresC fd_all_thrusters c_thruster_3)
    (isQAtype qa_water_visibility_low water_visibility)
    (solvesF fd_spiral_high f_generate_search_path)
    (hasQAestimation fd_spiral_low qa_search_efficiency_low)
    (solvesF fd_spiral_medium f_generate_search_path)
    (requiresC fd_all_thrusters c_thruster_2)
    (requiresC fd_all_thrusters c_thruster_5)
    (QAvalue obs_water_visibility)
    (FunctionDesign fd_spiral_medium)
    (QualityAttributeType water_visibility)
    (FunctionDesign fd_recover_thrusters)
    (FunctionDesign fd_follow_pipeline)
    (QAvalue qa_search_efficiency_high)
    (Function f_follow_pipeline)
    (Component c_thruster_2)
    (FunctionDesign fd_all_thrusters)
    (FunctionDesign fd_spiral_low)
    (Component c_thruster_3)
    (QAvalue qa_water_visibility_medium)
    (Function f_generate_search_path)
    (QualityAttributeType safety)
    (Component c_thruster_1)
    (QAvalue qa_water_visibility_high)
    (QualityAttributeType battery_level)
    (Component c_thruster_4)
    (QualityAttributeType performance)
    (Function f_maintain_motion)
    (QAvalue qa_water_visibility_low)
    (Component c_thruster_5)
    (QAvalue qa_search_efficiency_medium)
    (QAvalue qa_inspect_efficiency_high)
    (QAvalue qa_motion_efficiency_normal)
    (Component c_thruster_6)
    (FunctionDesign fd_spiral_high)
    (QAvalue qa_motion_efficiency_degraded)
    (QualityAttributeType energy)
    (QAvalue qa_search_efficiency_low)
  )

  (:goal (and
    (robot_started bluerov)
    (pipeline_found pipeline)
    (pipeline_inspected pipeline)
  ))
)
