(define (problem example-auv)
  (:domain suave)

  (:objects 
    f_generate_search_path f_follow_pipeline f_maintain_motion fd_spiral_low fd_spiral_medium fd_spiral_high fd_all_thrusters fd_recover_thrusters fd_follow_pipeline  <_string battery_level c_thruster_1 c_thruster_2 c_thruster_3 c_thruster_4 c_thruster_5 c_thruster_6 energy obs_water_visibility performance qa_inspect_efficiency_high qa_motion_efficiency_degraded qa_motion_efficiency_normal qa_search_efficiency_high qa_search_efficiency_low qa_search_efficiency_medium qa_water_visibility_high qa_water_visibility_low qa_water_visibility_medium safety - object 
    a_search_pipeline a_inspect_pipeline - action 
    pipeline - pipeline 
    bluerov - robot 
    2.0_decimal 3.25_decimal 0.25_decimal 0.5_decimal 0.75_decimal 1.0_decimal 1.25_decimal 2.25_decimal - number 
)

  (:init
    (fd_available fd_spiral_low)
    (fd_available fd_spiral_medium)
    (fd_available fd_spiral_high)
    (fd_available fd_all_thrusters)
    (fd_available fd_recover_thrusters)
    (fd_available fd_follow_pipeline)
    
    (a_search_pipeline_requires_f a_search_pipeline f_generate_search_path f_maintain_motion)
    (a_inspect_pipeline_requires_f a_inspect_pipeline f_follow_pipeline f_maintain_motion)
    
    (equalTo 0.25_decimal 0.25_decimal)
    (equalTo 0.5_decimal 0.5_decimal)
    (equalTo 0.75_decimal 0.75_decimal)
    (equalTo 1.0_decimal 1.0_decimal)
    (equalTo 1.25_decimal 1.25_decimal)
    (equalTo 2.0_decimal 2.0_decimal)
    (equalTo 2.25_decimal 2.25_decimal)
    (equalTo 3.25_decimal 3.25_decimal)
    (lessThan 0.25_decimal 0.5_decimal)
    (lessThan 0.25_decimal 0.75_decimal)
    (lessThan 0.25_decimal 1.0_decimal)
    (lessThan 0.25_decimal 1.25_decimal)
    (lessThan 0.25_decimal 2.0_decimal)
    (lessThan 0.25_decimal 2.25_decimal)
    (lessThan 0.25_decimal 3.25_decimal)
    (lessThan 0.5_decimal 0.75_decimal)
    (lessThan 0.5_decimal 1.0_decimal)
    (lessThan 0.5_decimal 1.25_decimal)
    (lessThan 0.5_decimal 2.0_decimal)
    (lessThan 0.5_decimal 2.25_decimal)
    (lessThan 0.5_decimal 3.25_decimal)
    (lessThan 0.75_decimal 1.0_decimal)
    (lessThan 0.75_decimal 1.25_decimal)
    (lessThan 0.75_decimal 2.0_decimal)
    (lessThan 0.75_decimal 2.25_decimal)
    (lessThan 0.75_decimal 3.25_decimal)
    (lessThan 1.0_decimal 1.25_decimal)
    (lessThan 1.0_decimal 2.0_decimal)
    (lessThan 1.0_decimal 2.25_decimal)
    (lessThan 1.0_decimal 3.25_decimal)
    (lessThan 1.25_decimal 2.0_decimal)
    (lessThan 1.25_decimal 2.25_decimal)
    (lessThan 1.25_decimal 3.25_decimal)
    (lessThan 2.0_decimal 2.25_decimal)
    (lessThan 2.0_decimal 3.25_decimal)
    (lessThan 2.25_decimal 3.25_decimal)
    
    (Component c_thruster_1)
    (Component c_thruster_2)
    (Component c_thruster_3)
    (Component c_thruster_4)
    (Component c_thruster_5)
    (Component c_thruster_6)
    (Function f_follow_pipeline)
    (Function f_generate_search_path)
    (Function f_maintain_motion)
    (FunctionDesign fd_all_thrusters)
    (FunctionDesign fd_follow_pipeline)
    (FunctionDesign fd_recover_thrusters)
    (FunctionDesign fd_spiral_high)
    (FunctionDesign fd_spiral_low)
    (FunctionDesign fd_spiral_medium)
    (QAvalue obs_water_visibility)
    (QAvalue qa_inspect_efficiency_high)
    (QAvalue qa_motion_efficiency_degraded)
    (QAvalue qa_motion_efficiency_normal)
    (QAvalue qa_search_efficiency_high)
    (QAvalue qa_search_efficiency_low)
    (QAvalue qa_search_efficiency_medium)
    (QAvalue qa_water_visibility_high)
    (QAvalue qa_water_visibility_low)
    (QAvalue qa_water_visibility_medium)
    (QualityAttributeType battery_level)
    (QualityAttributeType energy)
    (QualityAttributeType performance)
    (QualityAttributeType safety)
    (QualityAttributeType water_visibility)
    (hasQAestimation fd_all_thrusters qa_motion_efficiency_normal)
    (hasQAestimation fd_follow_pipeline qa_inspect_efficiency_high)
    (hasQAestimation fd_recover_thrusters qa_motion_efficiency_degraded)
    (hasQAestimation fd_spiral_high qa_search_efficiency_high)
    (hasQAestimation fd_spiral_high qa_water_visibility_high)
    (hasQAestimation fd_spiral_low qa_search_efficiency_low)
    (hasQAestimation fd_spiral_low qa_water_visibility_low)
    (hasQAestimation fd_spiral_medium qa_search_efficiency_medium)
    (hasQAestimation fd_spiral_medium qa_water_visibility_medium)
    (hasValue qa_inspect_efficiency_high 1.0_decimal)
    (hasValue qa_motion_efficiency_degraded 0.75_decimal)
    (hasValue qa_motion_efficiency_normal 1.0_decimal)
    (hasValue qa_search_efficiency_high 1.0_decimal)
    (hasValue qa_search_efficiency_low 0.25_decimal)
    (hasValue qa_search_efficiency_medium 0.5_decimal)
    (hasValue qa_water_visibility_high 3.25_decimal)
    (hasValue qa_water_visibility_low 1.25_decimal)
    (hasValue qa_water_visibility_medium 2.25_decimal)
    (isQAtype obs_water_visibility water_visibility)
    (isQAtype qa_inspect_efficiency_high performance)
    (isQAtype qa_motion_efficiency_degraded performance)
    (isQAtype qa_motion_efficiency_normal performance)
    (isQAtype qa_search_efficiency_high performance)
    (isQAtype qa_search_efficiency_low performance)
    (isQAtype qa_search_efficiency_medium performance)
    (isQAtype qa_water_visibility_high water_visibility)
    (isQAtype qa_water_visibility_low water_visibility)
    (isQAtype qa_water_visibility_medium water_visibility)
    (qa_comparison_operator battery_level <_string)
    (qa_comparison_operator water_visibility <_string)
    (requiredBy c_thruster_1 fd_all_thrusters)
    (requiredBy c_thruster_2 fd_all_thrusters)
    (requiredBy c_thruster_3 fd_all_thrusters)
    (requiredBy c_thruster_4 fd_all_thrusters)
    (requiredBy c_thruster_5 fd_all_thrusters)
    (requiredBy c_thruster_6 fd_all_thrusters)
    (solvesF fd_all_thrusters f_maintain_motion)
    (solvesF fd_follow_pipeline f_follow_pipeline)
    (solvesF fd_recover_thrusters f_maintain_motion)
    (solvesF fd_spiral_high f_generate_search_path)
    (solvesF fd_spiral_low f_generate_search_path)
    (solvesF fd_spiral_medium f_generate_search_path)
  )

  (:goal (and
    (robot_started bluerov)
    (pipeline_found pipeline)
    (pipeline_inspected pipeline)
  ))
)
